import type { Metadata } from "next";
import { Itim } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const ItimFont = Itim({
	weight: "400",
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${ItimFont.className} `}>
				<NavBar />
				{children}
			</body>
		</html>
	);
}
